### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by kalafut**
I will probably be taking my fork of this library in a different direction\* for a side project I'm working on, but I noticed that the tests weren't passing on master. Now they do.

Thanks,
Jim
- I'd like a tree representation, for starters.

### CODE REVIEW

**Comment by alexwlchan** [comment]
Thanks! Which version of Python were you running the tests against? I think I had them all passing when I left it, but was only using Python 3.

Separately, I have a half-baked tree implementation that I never got around to finishing. I can push that on a branch, if you’d like? (Or even finish it – I don’t think it’s that far from done, I just never got around to it.)

(Not at a computer where I can test this right now, will look at it properly later.)

**Comment by kalafut** [comment]
The 'span' issue failed universally and looks like an oops from a recent (post 0.3) change you made.

I'm using 2.7.10 and 3.5.1.  The 2.7 version would failure during a str() operation on an Item since Hypothesis was injecting unicode, I think.

I'd definitely like to take a look at that branch. Maybe you want to just add a few #TODO, #NOT DONE, etc. comments. I'd like to proceed fairly soon, and if it looks like your code is aligned with what I was going to do, all the better.

**Comment by alexwlchan** [comment]
Hmm, I seem to have mislaid this code. Sorry! :disappointed: 

I'll merge this now, and then get Travis CI runs against it shortly, so that I don't break it again. I might get around to reproducing my tree code, but no promises. (I'd sort of assumed nobody was using this, so it was never high enough on my todo list to get around to working on it.)

Thanks for the fix!

**Comment by kalafut** [comment]
OK. My tree implementation was going to be pretty simple anyway, so I might just get going on it. I'll let you know where I get to, and if the implementation or API are similar maybe things get consolidated.

**Pull request merged**
